# Generated by Django 4.2.3 on 2023-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
